In [1]:
import numpy as np

In [7]:
int_arr = np.random.randint(0, 10, 10)

In [5]:
int_arr

NameError: name 'int_arr' is not defined

In [6]:
int_arr

NameError: name 'int_arr' is not defined

In [8]:
int_arr

array([0, 8, 8, 2, 4, 9, 3, 0, 9, 2])

In [9]:
int_arr[0]

0

In [10]:
int_arr[9]

2

In [11]:
int_arr[1:3]

array([8, 8])

In [12]:
int_arr[1:7]

array([8, 8, 2, 4, 9, 3])

In [13]:
int_arr[0:4]

array([0, 8, 8, 2])

In [14]:
int_arr[:4]

array([0, 8, 8, 2])

In [15]:
int_arr[4:10]

array([4, 9, 3, 0, 9, 2])

In [16]:
int_arr[4:]

array([4, 9, 3, 0, 9, 2])

In [17]:
int_arr[4:10] = 10

In [18]:
int_arr

array([ 0,  8,  8,  2, 10, 10, 10, 10, 10, 10])

In [19]:
arr = np.arange(0, 10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
new_arr = arr[:4]

In [22]:
new_arr

array([0, 1, 2, 3])

In [23]:
new_arr[2:] = 7


In [24]:
new_arr

array([0, 1, 7, 7])

In [25]:
arr

array([0, 1, 7, 7, 4, 5, 6, 7, 8, 9])

In [26]:
arr = np.arange(0, 10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
new_arr = arr.copy()

In [29]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
new_arr[:] = 0

In [31]:
new_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [34]:
bool_arr = arr > 6

In [35]:
bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [36]:
arr[bool_arr]

array([7, 8, 9])

In [37]:
bool_arr = arr > 0


In [38]:
arr[bool_arr]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[arr > 0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr[arr < 5]

array([0, 1, 2, 3, 4])