In [5]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

Docstring shortcut 'Shift + Tab'

In [2]:
odd_number_list = [1, 3, 5, 7]

In [3]:
np.array(odd_number_list)

array([1, 3, 5, 7])

In [4]:
two_dim_list = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
np.array(two_dim_list)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [16]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(3)

array([0.41451619, 0.32686795, 0.3730553 ])

In [21]:
np.random.rand(7)

array([0.97060918, 0.53952901, 0.2184427 , 0.60904018, 0.119664  ,
       0.87167958, 0.83446323])

In [22]:
np.random.rand(3, 4)

array([[0.92429423, 0.6330861 , 0.61389746, 0.25286318],
       [0.7232677 , 0.66259916, 0.54101045, 0.4784357 ],
       [0.68778721, 0.7956402 , 0.74728615, 0.44795494]])

In [23]:
np.random.randn(3)

array([1.36950835, 0.4368247 , 0.33851085])

In [24]:
np.random.randn(5)

array([ 0.83305871,  1.23485923,  0.75241833, -0.96251747,  0.32550691])

In [25]:
np.random.randn(3, 5)

array([[-0.85576117,  0.67220836,  0.11866855,  1.70944427,  0.4239267 ],
       [ 1.04616309,  0.07303193, -1.243239  , -0.57719553,  0.43555695],
       [ 0.61782344,  1.27263573,  0.83781399,  0.98638162, -0.74726525]])

In [26]:
np.random.randint(0, 50, 20)

array([24, 25, 41, 39, 37,  4, 16, 10, 49,  0,  9, 41, 25, 15, 29, 19, 36,
        2, 48,  4])

In [27]:
rand_arr = np.random.randint(0, 50, 20)

In [28]:
rand_arr 

array([36, 48, 34, 33,  1, 25, 42,  5, 41, 22, 10, 17, 12, 29, 33, 37,  0,
       24, 22, 22])

In [29]:
second_arr = np.arange(20)

In [30]:
second_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
rand_arr.reshape(4, 5)

array([[36, 48, 34, 33,  1],
       [25, 42,  5, 41, 22],
       [10, 17, 12, 29, 33],
       [37,  0, 24, 22, 22]])

In [33]:
rand_arr.reshape(5, 4)

array([[36, 48, 34, 33],
       [ 1, 25, 42,  5],
       [41, 22, 10, 17],
       [12, 29, 33, 37],
       [ 0, 24, 22, 22]])

In [34]:
second_arr.reshape(2, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [35]:
second_arr.max()

19

In [36]:
second_arr.min()

0

In [37]:
second_arr.argmax()

19

In [38]:
rand_arr.max()

48

In [39]:
rand_arr.argmax()

1

In [40]:
rand_arr.min()

0

In [41]:
rand_arr.argmin()

16

In [42]:
second_arr.shape

(20,)

In [43]:
reshaped_arr = second_arr.reshape(2, 10)

In [44]:
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [45]:
reshaped_arr.shape

(2, 10)

In [46]:
reshaped_arr.dtype

dtype('int64')